### ISSUE TITLE
Create group is not working

### ISSUE THREAD

**Issue by manojsitapara** [open-wa/wa-automate-python#5]
I am using following code to create new whatsapp group but it seems not working, it gives timeout error, anyone can help?

`driver.create_group('Test15',{'id': "XXXXX@c.us"}) `

I have tried to solve as suggested in following link, but still no luck

[https://github.com/mukulhase/WebWhatsapp-Wrapper/issues/749](https://github.com/mukulhase/WebWhatsapp-Wrapper/issues/749)

**UPDATE:**

It seems working after modifying following code 

`   window.WAPI.createGroup = async function (name, contactsId) {
      if (!Array.isArray(contactsId)) {
        contactsId = [contactsId];
      }
      return await window.Store.Wap.createGroup(name, 0, 0, contactsId);
    };  `

but it never return any value, it keep processing and getting following error

>Error in function createGroup (Timed out after 60000 ms). Command: return WAPI.createGroup('Test15',{'id': 'xxxxxx@c.us'}, arguments[0])

Can you please help me to fix issue?

**Comment by mrodal** [comment]
Thanks for reporting
Its fixed now, please download the latest version

**Comment by manojsitapara** [comment]
It gives following error after fix

> Error in function createGroup (SyntaxError: missing : after property id). Command: return WAPI.createGroup('Test16',{'xxxx@c.us'}, arguments[0])

**Comment by manojsitapara** [comment]
> Thanks for reporting
> Its fixed now, please download the latest version

It gives following error after fix

>Error in function createGroup (SyntaxError: missing : after property id). Command: return WAPI.createGroup('Test16',{'xxxx@c.us'}, arguments[0])

**Comment by manojsitapara** [comment]
In case if someone need help. here is example to creategroup

contacts = ["12058528526@c.us"]
status = driver.create_group('Test17',contacts)

**Comment by Meet2308** [comment]
> In case if someone need help. here is example to creategroup
> 
> contacts = ["[12058528526@c.us](mailto:12058528526@c.us)"]
> status = driver.create_group('Test17',contacts)

i do the same thing but get still get error:
`webwhatsapi.wapi_js_wrapper.JsException: Error in function createGroup (javascript error: Cannot read property 'map' of undefined
`
`  (Session info: headless chrome=80.0.3987.116)). Command: return WAPI.createGroup('testing',['919408836525@c.us'], arguments[0])
`
